version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "bot"
    commit_message:
      prefix: "dependabot:"
      include_scope: true
