trigger:
  branches:
    include:
      - master
      - rel/*
  tags:
    include:
    - 'v*'
pr:
  branches:
    include:
      - master
      - rel/*

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.301'
    includePreviewVersions: true
  displayName: 'Install .NET SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '/t:UpdateAzureDevOpsBuildNumber'
  displayName: 'Update Build Number'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    configuration: $(BuildConfiguration)
    arguments: '-p:EnableCoverage=true'
    publishTestResults: true
  displayName: 'Test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: $(BuildConfiguration)
    outputDir: '$(Build.ArtifactStagingDirectory)/packages'
    verbosityPack: Minimal
  displayName: 'Package NuGets'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/packages'
    ArtifactName: 'Packages'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './CHANGELOG.md'
    ArtifactName: 'ReleaseNotes'