trigger:
  - master

pool:
  vmImage: 'windows-2019'

steps:
- template: build/azdo-corebuild.yml
  parameters:
    buildType: 'prerelease'

- task: DotNetCoreCLI@2
  inputs:
    command: push
    feedPublish: 'NXPorts-Nightly'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'