trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  BuildType: 'prerelease'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.301'
    includePreviewVersions: true
  displayName: 'Install .NET SDK'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'Test'
- script: dotnet pack --configuration $(buildConfiguration)
  displayName: 'Package NuGets'